
dist: trusty
sudo: required
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - cmake
install:
  - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
  - export CXX=/usr/bin/g++-8
  - g++ --version
  - cmake --version
script:
  - mkdir build
  - cd build
  - cmake .. 
  - cmake --build .
  - ctest -V
