
version: '{build}'
image: Visual Studio 2017
configuration:
  - Release
  - Debug
platform:
  - x64
branches:
  except:
    - master
build_script:
  - mkdir build
  - cd build
  - cmake .. 
  - cmake --build .
  - ctest -V
